name = "cloudinary-delete"
compatibility_date = "2025-07-05"
main = "src/index.ts"

compatibility_flags = ["nodejs_compat"]

[build]
command = "npm install"

[vars]
CLOUDINARY_CLOUD_NAME = ""
CLOUDINARY_API_KEY = ""
CLOUDINARY_API_SECRET = ""
